version: "3.7"
name: "root-postgres-backup"
services:
  root-postgres-rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    hostname: root-postgres-rabbitmq
    container_name: root-postgres-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - "${RABBIT_STORE_LOCATION}:/var/lib/rabbitmq/mnesia"
    ports:
      - "${RABBIT_GUI_PORT}:15672"
      - "${RABBIT_MONITORING_PORT}:15692"
      - "${RABBIT_PORT}:5672"
    networks:
      - root-postgres-network
networks:
  root-postgres-network:
    driver: bridge